### ISSUE TITLE
Syntax issue

### ISSUE THREAD

**Issue by BeeGass** [ShayBox/OnePasswordConverter#1]
Had an issue when running `convert`  command

`convert file.1pux`
```
File "~/.local/bin/convert", line 5
    from 1passwordconverter.main import main
         ^
SyntaxError: invalid syntax
```

I was hoping you could help if this is an issue on my end

**Comment by ShayBox** [comment]
Make sure you're using Python 3.6 - 3.9 and you install it with the poetry instructions in the readme, I believe that error means it can't find the 1passwordconverter package in your pip installation

**Comment by ShayBox** [comment]
I found the issue and renamed the project, it was because of the 1 in the name.
